In [1]:
import numpy as np

In [4]:
#working with numpy array
arr1 = np.array([5, 8, 9, 14, 28, 39, 23, 45, 88, 72])
print("1D array:", arr1)

print("\n Average number:", arr1. mean())

print("\n Standard Deviation:", arr1. std())

1D array: [ 5  8  9 14 28 39 23 45 88 72]

 Average number: 33.1

 Standard Deviation: 26.827038599144707


In [11]:
#2D array using Index and slicing
arr2 = np .array([
    [3, 4, 5],
    [6, 7, 8],
    [9, 10, 11]
])
print(arr2)

print("\n", arr2[0, 2])
print(arr2[2,:2])
print(arr2[1:2, 2])
print(arr2[1, :2])
print(arr2[0, :])

[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

 5
[ 9 10]
[8]
[6 7]
[3 4 5]


In [14]:
#1D to 2D array
arr3 = np.arange(20, 41)
reshape = arr3.reshape(3, 7)

print("Array numbers:", arr3)
print("Reshape 1D array into 2D array:\n", reshape)

flatten = reshape.flatten()

#convert 2D to 1D array
print("Flatten array:", flatten)

Array numbers: [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40]
Reshape 1D array into 2D array:
 [[20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33]
 [34 35 36 37 38 39 40]]
Flatten array: [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40]
